#!/usr/bin/env node
// combined-report.mjs — the two-lane composed report GENERATOR (M9 fix). The founder-facing combined
// report was previously hand-authored static HTML with hand-typed inline data — which is exactly how a
// fabricated finding (an invalid-selector main-content-missing artifact) slipped in at the same severity
// as a genuine WCAG violation. This generator reads BOTH lanes' REAL JSON output and renders the HTML,
// so the artifact's correctness is a function of tested code, not manual transcription. The two lanes
// are composed side-by-side, never fused into one blended score (S23/D6).
//
// Usage: node scripts/combined-report.mjs --persona <findings.json> --structural <structural.json> [--out <file>]
import { readFileSync, writeFileSync } from 'node:fs';

function arg(name, def) { const i = process.argv.indexOf(`--${name}`); return i > -1 ? process.argv[i + 1] : def; }
const personaPath = arg('persona');
const structuralPath = arg('structural');
const outPath = arg('out');
if (!personaPath || !structuralPath) {
  process.stderr.write('usage: combined-report.mjs --persona <findings.json> --structural <structural.json> [--out <file>]\n');
  process.exit(2);
}

const persona = JSON.parse(readFileSync(personaPath, 'utf8'));
const structural = JSON.parse(readFileSync(structuralPath, 'utf8'));

const SEV_COLOR = { 4: '#c0392b', 3: '#e67e22', 2: '#f1c40f', 1: '#95a5a6', 0: '#5d6b7a' };
const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const sevBadge = (s) => `<span class="sev" style="background:${SEV_COLOR[s] ?? '#5d6b7a'}">S${s}</span>`;

const personaFindings = (persona.findings || []).slice()
  .sort((a, b) => (b.convergence_tier || 0) - (a.convergence_tier || 0) || (b.severity || 0) - (a.severity || 0));
const personaCards = personaFindings.map((f) => {
  const tier = f.convergence_tier ?? (f.personas_flagging || []).length;
  const total = (persona.personas || persona.run?.personas || []).length || tier;
  return `<div class="card"><div class="h">${sevBadge(f.severity)}<span class="tier">flagged by ${tier}/${total}</span><span class="tag">${esc(f.heuristic_tag)}</span></div><b>${esc(f.friction_name)}</b><div class="tgt">${esc(f.target_element_identifier || '')}</div></div>`;
}).join('');

const structuralFindings = (structural.findings || []).slice().sort((a, b) => (b.severity || 0) - (a.severity || 0));
const structuralCards = structuralFindings.map((f) => {
  const src = f.source ?? (typeof f.code === 'string' && f.code.startsWith('axe:') ? 'axe' : 'dom-check');
  return `<div class="card"><div class="h">${sevBadge(f.severity)}<span class="tag">${esc(src)}·${esc(f.code)}</span><span class="raw">${esc(f.impact || '')}</span></div><b>${esc(f.help || f.detail || f.code)}</b><div class="tgt">${esc(f.target_element_identifier || f.target_selector || '')}</div></div>`;
}).join('');

const target = persona.run?.target_name || structural.run?.url || 'target';
const html = `<!doctype html><html><head><meta charset="utf-8"><title>ux-gauntlet — two lanes, one target</title><style>
body{margin:0;font:15px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;background:#0f1216;color:#e7ebf0}
.wrap{max-width:900px;margin:0 auto;padding:30px 20px 70px} h1{font-size:27px;margin:0 0 3px}
.muted{color:#8b97a5;font-size:14px} .lanes{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:22px}
@media(max-width:680px){.lanes{grid-template-columns:1fr}}
.lane h2{font-size:16px;margin:0 0 4px} .lane .sub{color:#8b97a5;font-size:12.5px;margin-bottom:10px}
.card{background:#161b22;border:1px solid #232a33;border-radius:11px;padding:11px 13px;margin:8px 0}
.h{display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin-bottom:5px}
.sev{color:#fff;font-weight:700;font-size:11px;padding:2px 7px;border-radius:12px}
.tier{font-size:11px;color:#8fb4ff;border:1px solid #2f6df6;border-radius:12px;padding:2px 7px}
.tag{font-size:11px;color:#9fb0c0;background:#1d242d;padding:2px 7px;border-radius:5px} .raw{font-size:11px;color:#c9a3ff}
.card b{font-size:13.5px;font-weight:600} .tgt{font-size:11px;color:#6b7885;margin-top:3px;font-family:monospace}
.pill{display:inline-block;background:#12233f;color:#8fb4ff;border:1px solid #2f6df6;border-radius:12px;padding:1px 9px;font-size:11px}
.env{background:#12161c;border:1px solid #232a33;border-radius:10px;padding:13px 15px;margin-top:22px;font-size:12px;color:#93a1b0}</style></head><body><div class="wrap">
<h1>ux-gauntlet — two lanes, one target</h1>
<div class="muted">Real crawl · <span class="pill">${esc(target)} · localhost:4319</span> · generated by scripts/combined-report.mjs from both lanes' JSON · the two lanes compose, never fuse into one score</div>
<div class="lanes">
<div class="lane"><h2>🎭 Persona friction (UX)</h2><div class="sub">subjective · ${(persona.personas || persona.run?.personas || []).length} LLM buyer-personas · ${personaFindings.length} grounded findings ranked by cross-persona convergence</div>
${personaCards}</div>
<div class="lane"><h2>🔩 Structural (UI)</h2><div class="sub">deterministic · axe-core ${esc(structural.metadata?.axe_version || '')} + semantics + main-content · ${structuralFindings.length} findings, no LLM</div>
${structuralCards}</div>
</div>
<div class="env"><b>Why two lanes</b> — The persona lane answers "is this <i>usable</i> for a buyer?" (subjective, convergence-tiered, findings grounded against the captured trace). The structural lane answers "is the UI <i>code-correct</i>?" (deterministic: WCAG via axe, landmarks, is the declared main content structurally the main content, is the continue control a real focusable button). Automated a11y catches only ~32-57% of WCAG (vendor-reported) — a structural pass is necessary, not sufficient; not "usable", not "good UI". Neither lane is a replacement for real user research.</div>
</div></body></html>`;

if (outPath) { writeFileSync(outPath, html); process.stderr.write(`combined-report: wrote ${outPath} (${personaFindings.length} persona + ${structuralFindings.length} structural)\n`); }
else process.stdout.write(html);
